name: Update MERN Chart

on:
  schedule:
    - cron: '0 0 * * *' # Run daily
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios chartjs-node-canvas

      - name: Analyze Repositories
        run: node analyze_repos.js

      - name: Generate Chart
        run: node generate_chart.js

      - name: Commit and Push Changes
        run: |
          git config user.name 'github-actions'
          git config user.email 'actions@github.com'
          git add .
          git commit -m 'Update MERN chart'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
